CREATE TABLE `responsavel` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(200) NULL DEFAULT NULL,
	`cpf` VARCHAR(20) NULL DEFAULT NULL,
	`telefone` VARCHAR(20) NULL DEFAULT NULL,
	`email` VARCHAR(70) NULL DEFAULT NULL,
	`endereco` VARCHAR(150) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)