CREATE TABLE `professor` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(200) NOT NULL DEFAULT '0',
	`materia` VARCHAR(200) NOT NULL DEFAULT '0',
	`telefone` VARCHAR(20) NOT NULL DEFAULT '0',
	`email` VARCHAR(70) NOT NULL DEFAULT '0',
	`endereco` VARCHAR(150) NOT NULL DEFAULT '0',
	PRIMARY KEY (`Coluna 1`)
)